using Microsoft.EntityFrameworkCore;

namespace BankAccountOpening.Models
{
    public static class ModelBuilderExtension
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<States>().HasData(
            new States { StateId = 1, StateName = "Andhra Pradesh" },
            new States { StateId = 2, StateName = "Arunachal Pradesh" },
            new States { StateId = 3, StateName = "Assam" },
            new States { StateId = 4, StateName = "Bihar" },
            new States { StateId = 5, StateName = "Chhattisgarh" },
            new States { StateId = 6, StateName = "Goa" },
            new States { StateId = 7, StateName = "Gujarat" },
            new States { StateId = 8, StateName = "Haryana" },
            new States { StateId = 9, StateName = "Himachal Pradesh" },
            new States { StateId = 10, StateName = "Jharkhand" },
            new States { StateId = 11, StateName = "Karnataka" },
            new States { StateId = 12, StateName = "Kerala" },
            new States { StateId = 13, StateName = "Madhya Pradesh" },
            new States { StateId = 14, StateName = "Maharashtra" },
            new States { StateId = 15, StateName = "Manipur" },
            new States { StateId = 16, StateName = "Meghalaya" },
            new States { StateId = 17, StateName = "Mizoram" },
            new States { StateId = 18, StateName = "Nagaland" },
            new States { StateId = 19, StateName = "Odisha" },
            new States { StateId = 20, StateName = "Punjab" },
            new States { StateId = 21, StateName = "Rajasthan" },
            new States { StateId = 22, StateName = "Sikkim" },
            new States { StateId = 23, StateName = "Tamil Nadu" },
            new States { StateId = 24, StateName = "Telangana" },
            new States { StateId = 25, StateName = "Tripura" },
            new States { StateId = 26, StateName = "Uttar Pradesh" },
            new States { StateId = 27, StateName = "Uttarakhand" },
            new States { StateId = 28, StateName = "West Bengal" },
            new States { StateId = 29, StateName = "Andaman and Nicobar Islands" },
            new States { StateId = 30, StateName = "Chandigarh" },
            new States { StateId = 31, StateName = "Dadra and Nagar Haveli and Daman and Diu" },
            new States { StateId = 32, StateName = "Delhi" },
            new States { StateId = 33, StateName = "Jammu and Kashmir" },
            new States { StateId = 34, StateName = "Ladakh" },
            new States { StateId = 35, StateName = "Lakshadweep" },
            new States { StateId = 36, StateName = "Puducherry" }
            );

            modelBuilder.Entity<Cities>().HasData(
            new Cities { CityId = 1, CityName = "Mumbai", CityStateCode = 14 },
            new Cities { CityId = 2, CityName = "Pune", CityStateCode = 14 },
            new Cities { CityId = 3, CityName = "Bangalore", CityStateCode = 11 },
            new Cities { CityId = 4, CityName = "Delhi", CityStateCode = 7 },
            new Cities { CityId = 5, CityName = "Chennai", CityStateCode = 13 },
            new Cities { CityId = 6, CityName = "Kolkata", CityStateCode = 19 },
            new Cities { CityId = 7, CityName = "Hyderabad", CityStateCode = 36 },
            new Cities { CityId = 8, CityName = "Ahmedabad", CityStateCode = 24 },
            new Cities { CityId = 9, CityName = "Jaipur", CityStateCode = 8 },
            new Cities { CityId = 10, CityName = "Surat", CityStateCode = 24 },
            new Cities { CityId = 11, CityName = "Lucknow", CityStateCode = 9 },
            new Cities { CityId = 12, CityName = "Kanpur", CityStateCode = 9 },
            new Cities { CityId = 13, CityName = "Nagpur", CityStateCode = 21 },
            new Cities { CityId = 14, CityName = "Indore", CityStateCode = 23 },
            new Cities { CityId = 15, CityName = "Thane", CityStateCode = 14 },
            new Cities { CityId = 16, CityName = "Chandigarh", CityStateCode = 4 },
            new Cities { CityId = 17, CityName = "Patna", CityStateCode = 10 },
            new Cities { CityId = 18, CityName = "Vadodara", CityStateCode = 24 },
            new Cities { CityId = 19, CityName = "Coimbatore", CityStateCode = 13 },
            new Cities { CityId = 20, CityName = "Visakhapatnam", CityStateCode = 36 },
            new Cities { CityId = 21, CityName = "Bhopal", CityStateCode = 23 },
            new Cities { CityId = 22, CityName = "Nashik", CityStateCode = 14 },
            new Cities { CityId = 23, CityName = "Faridabad", CityStateCode = 7 },
            new Cities { CityId = 24, CityName = "Rajkot", CityStateCode = 24 },
            new Cities { CityId = 25, CityName = "Meerut", CityStateCode = 9 },
            new Cities { CityId = 26, CityName = "Noida", CityStateCode = 7 },
            new Cities { CityId = 27, CityName = "Shivamogga", CityStateCode = 11 },
            new Cities { CityId = 28, CityName = "Mysuru", CityStateCode = 11 },
            new Cities { CityId = 29, CityName = "Agra", CityStateCode = 9 },
            new Cities { CityId = 30, CityName = "Raipur", CityStateCode = 36 },
            new Cities { CityId = 31, CityName = "Vijayawada", CityStateCode = 36 },
            new Cities { CityId = 32, CityName = "Kochi", CityStateCode = 13 },
            new Cities { CityId = 33, CityName = "Gurgaon", CityStateCode = 7 },
            new Cities { CityId = 34, CityName = "Kozhikode", CityStateCode = 13 },
            new Cities { CityId = 35, CityName = "Ranchi", CityStateCode = 20 },
            new Cities { CityId = 36, CityName = "Howrah", CityStateCode = 19 },
            new Cities { CityId = 37, CityName = "Dhanbad", CityStateCode = 20 },
            new Cities { CityId = 38, CityName = "Jabalpur", CityStateCode = 23 },
            new Cities { CityId = 39, CityName = "Gwalior", CityStateCode = 23 },
            new Cities { CityId = 40, CityName = "Durgapur", CityStateCode = 19 },
            new Cities { CityId = 41, CityName = "Bhubaneswar", CityStateCode = 21 },
            new Cities { CityId = 42, CityName = "Tiruchirappalli", CityStateCode = 13 },
            new Cities { CityId = 43, CityName = "Vellore", CityStateCode = 13 },
            new Cities { CityId = 44, CityName = "Puducherry", CityStateCode = 15 },
            new Cities { CityId = 45, CityName = "Shimla", CityStateCode = 2 },
            new Cities { CityId = 46, CityName = "Dehradun", CityStateCode = 2 },
            new Cities { CityId = 47, CityName = "Mangalore", CityStateCode = 11 },
            new Cities { CityId = 48, CityName = "Gandhinagar", CityStateCode = 24 },
            new Cities { CityId = 49, CityName = "Srinagar", CityStateCode = 1 },
            new Cities { CityId = 50, CityName = "Amritsar", CityStateCode = 3 },
            new Cities { CityId = 51, CityName = "Allahabad", CityStateCode = 9 },
            new Cities { CityId = 52, CityName = "Bikaner", CityStateCode = 8 },
            new Cities { CityId = 53, CityName = "Jodhpur", CityStateCode = 8 },
            new Cities { CityId = 54, CityName = "Nagapattinam", CityStateCode = 13 },
            new Cities { CityId = 55, CityName = "Siliguri", CityStateCode = 19 },
            new Cities { CityId = 56, CityName = "Solapur", CityStateCode = 14 },
            new Cities { CityId = 57, CityName = "Cuttack", CityStateCode = 21 },
            new Cities { CityId = 58, CityName = "Udaipur", CityStateCode = 8 },
            new Cities { CityId = 59, CityName = "Raigarh", CityStateCode = 36 },
            new Cities { CityId = 60, CityName = "Haridwar", CityStateCode = 2 },
            new Cities { CityId = 61, CityName = "Kurnool", CityStateCode = 36 },
            new Cities { CityId = 62, CityName = "Jammu", CityStateCode = 1 },
            new Cities { CityId = 63, CityName = "Aurangabad", CityStateCode = 14 },
            new Cities { CityId = 64, CityName = "Bilaspur", CityStateCode = 23 },
            new Cities { CityId = 65, CityName = "Nellore", CityStateCode = 36 },
            new Cities { CityId = 66, CityName = "Erode", CityStateCode = 13 },
            new Cities { CityId = 67, CityName = "Tirunelveli", CityStateCode = 13 },
            new Cities { CityId = 68, CityName = "Warangal", CityStateCode = 36 },
            new Cities { CityId = 69, CityName = "Khammam", CityStateCode = 36 },
            new Cities { CityId = 70, CityName = "Muzaffarpur", CityStateCode = 10 },
            new Cities { CityId = 71, CityName = "Moradabad", CityStateCode = 9 },
            new Cities { CityId = 72, CityName = "Bihar Sharif", CityStateCode = 10 },
            new Cities { CityId = 73, CityName = "Shirdi", CityStateCode = 14 },
            new Cities { CityId = 74, CityName = "Guwahati", CityStateCode = 3 },
            new Cities { CityId = 75, CityName = "Rourkela", CityStateCode = 21 },
            new Cities { CityId = 76, CityName = "Bhilai", CityStateCode = 20 },
            new Cities { CityId = 77, CityName = "Madurai", CityStateCode = 13 },
            new Cities { CityId = 78, CityName = "Chandrapur", CityStateCode = 14 },
            new Cities { CityId = 79, CityName = "Ludhiana", CityStateCode = 3 },
            new Cities { CityId = 80, CityName = "Bilaspur", CityStateCode = 23 },
            new Cities { CityId = 81, CityName = "Kochi", CityStateCode = 13 },
            new Cities { CityId = 82, CityName = "Karur", CityStateCode = 13 },
            new Cities { CityId = 83, CityName = "Ambala", CityStateCode = 4 },
            new Cities { CityId = 84, CityName = "Haldwani", CityStateCode = 2 },
            new Cities { CityId = 85, CityName = "Aligarh", CityStateCode = 9 },
            new Cities { CityId = 86, CityName = "Tumkur", CityStateCode = 11 },
            new Cities { CityId = 87, CityName = "Sangli", CityStateCode = 14 },
            new Cities { CityId = 88, CityName = "Kolar", CityStateCode = 11 },
            new Cities { CityId = 89, CityName = "Jamshedpur", CityStateCode = 20 },
            new Cities { CityId = 90, CityName = "Rohtak", CityStateCode = 7 },
            new Cities { CityId = 91, CityName = "Shivpuri", CityStateCode = 23 },
            new Cities { CityId = 92, CityName = "Durgapur", CityStateCode = 19 },
            new Cities { CityId = 93, CityName = "Hoshiarpur", CityStateCode = 3 },
            new Cities { CityId = 94, CityName = "Gurgaon", CityStateCode = 7 },
            new Cities { CityId = 95, CityName = "Satna", CityStateCode = 23 },
            new Cities { CityId = 96, CityName = "Pondicherry", CityStateCode = 15 },
            new Cities { CityId = 97, CityName = "Baroda", CityStateCode = 24 },
            new Cities { CityId = 98, CityName = "Tumkur", CityStateCode = 11 },
            new Cities { CityId = 99, CityName = "Raichur", CityStateCode = 11 },
            new Cities { CityId = 100, CityName = "Vapi", CityStateCode = 24 }
            );

            var branches = new List<Branch>();
            for (int i = 1; i < 101; i++)
            {
                branches.Add(new Branch
                {
                    BranchCode = i,
                    BranchName = $"Branch {i}",
                    BranchCityCode = (i % 36) + 1
                });
            }

            modelBuilder.Entity<Branch>().HasData(branches);

            modelBuilder.Entity<Languages>().HasData(
                new Languages { languageCode = 1, languageName = "Hindi" },
                new Languages { languageCode = 2, languageName = "Bengali" },
                new Languages { languageCode = 3, languageName = "Telugu" },
                new Languages { languageCode = 4, languageName = "Marathi" },
                new Languages { languageCode = 5, languageName = "Tamil" },
                new Languages { languageCode = 6, languageName = "Urdu" },
                new Languages { languageCode = 7, languageName = "Gujarati" },
                new Languages { languageCode = 8, languageName = "Malayalam" },
                new Languages { languageCode = 9, languageName = "Punjabi" },
                new Languages { languageCode = 10, languageName = "Odia" },
                new Languages { languageCode = 11, languageName = "Kannada" },
                new Languages { languageCode = 12, languageName = "Assamese" },
                new Languages { languageCode = 13, languageName = "Maithili" },
                new Languages { languageCode = 14, languageName = "Santali" },
                new Languages { languageCode = 15, languageName = "Konkani" }
            );
        }
    }
}
