// <auto-generated />
using System;
using BankAccountOpening.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountOpening.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250426091524_Added Age columns to Users table")]
    partial class AddedAgecolumnstoUserstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankAccountOpening.Models.Branch", b =>
                {
                    b.Property<int>("BranchCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchCode"));

                    b.Property<int>("BranchCityCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BranchCode");

                    b.ToTable("branches");

                    b.HasData(
                        new
                        {
                            BranchCode = 1,
                            BranchCityCode = 2,
                            BranchName = "Branch 1"
                        },
                        new
                        {
                            BranchCode = 2,
                            BranchCityCode = 3,
                            BranchName = "Branch 2"
                        },
                        new
                        {
                            BranchCode = 3,
                            BranchCityCode = 4,
                            BranchName = "Branch 3"
                        },
                        new
                        {
                            BranchCode = 4,
                            BranchCityCode = 5,
                            BranchName = "Branch 4"
                        },
                        new
                        {
                            BranchCode = 5,
                            BranchCityCode = 6,
                            BranchName = "Branch 5"
                        },
                        new
                        {
                            BranchCode = 6,
                            BranchCityCode = 7,
                            BranchName = "Branch 6"
                        },
                        new
                        {
                            BranchCode = 7,
                            BranchCityCode = 8,
                            BranchName = "Branch 7"
                        },
                        new
                        {
                            BranchCode = 8,
                            BranchCityCode = 9,
                            BranchName = "Branch 8"
                        },
                        new
                        {
                            BranchCode = 9,
                            BranchCityCode = 10,
                            BranchName = "Branch 9"
                        },
                        new
                        {
                            BranchCode = 10,
                            BranchCityCode = 11,
                            BranchName = "Branch 10"
                        },
                        new
                        {
                            BranchCode = 11,
                            BranchCityCode = 12,
                            BranchName = "Branch 11"
                        },
                        new
                        {
                            BranchCode = 12,
                            BranchCityCode = 13,
                            BranchName = "Branch 12"
                        },
                        new
                        {
                            BranchCode = 13,
                            BranchCityCode = 14,
                            BranchName = "Branch 13"
                        },
                        new
                        {
                            BranchCode = 14,
                            BranchCityCode = 15,
                            BranchName = "Branch 14"
                        },
                        new
                        {
                            BranchCode = 15,
                            BranchCityCode = 16,
                            BranchName = "Branch 15"
                        },
                        new
                        {
                            BranchCode = 16,
                            BranchCityCode = 17,
                            BranchName = "Branch 16"
                        },
                        new
                        {
                            BranchCode = 17,
                            BranchCityCode = 18,
                            BranchName = "Branch 17"
                        },
                        new
                        {
                            BranchCode = 18,
                            BranchCityCode = 19,
                            BranchName = "Branch 18"
                        },
                        new
                        {
                            BranchCode = 19,
                            BranchCityCode = 20,
                            BranchName = "Branch 19"
                        },
                        new
                        {
                            BranchCode = 20,
                            BranchCityCode = 21,
                            BranchName = "Branch 20"
                        },
                        new
                        {
                            BranchCode = 21,
                            BranchCityCode = 22,
                            BranchName = "Branch 21"
                        },
                        new
                        {
                            BranchCode = 22,
                            BranchCityCode = 23,
                            BranchName = "Branch 22"
                        },
                        new
                        {
                            BranchCode = 23,
                            BranchCityCode = 24,
                            BranchName = "Branch 23"
                        },
                        new
                        {
                            BranchCode = 24,
                            BranchCityCode = 25,
                            BranchName = "Branch 24"
                        },
                        new
                        {
                            BranchCode = 25,
                            BranchCityCode = 26,
                            BranchName = "Branch 25"
                        },
                        new
                        {
                            BranchCode = 26,
                            BranchCityCode = 27,
                            BranchName = "Branch 26"
                        },
                        new
                        {
                            BranchCode = 27,
                            BranchCityCode = 28,
                            BranchName = "Branch 27"
                        },
                        new
                        {
                            BranchCode = 28,
                            BranchCityCode = 29,
                            BranchName = "Branch 28"
                        },
                        new
                        {
                            BranchCode = 29,
                            BranchCityCode = 30,
                            BranchName = "Branch 29"
                        },
                        new
                        {
                            BranchCode = 30,
                            BranchCityCode = 31,
                            BranchName = "Branch 30"
                        },
                        new
                        {
                            BranchCode = 31,
                            BranchCityCode = 32,
                            BranchName = "Branch 31"
                        },
                        new
                        {
                            BranchCode = 32,
                            BranchCityCode = 33,
                            BranchName = "Branch 32"
                        },
                        new
                        {
                            BranchCode = 33,
                            BranchCityCode = 34,
                            BranchName = "Branch 33"
                        },
                        new
                        {
                            BranchCode = 34,
                            BranchCityCode = 35,
                            BranchName = "Branch 34"
                        },
                        new
                        {
                            BranchCode = 35,
                            BranchCityCode = 36,
                            BranchName = "Branch 35"
                        },
                        new
                        {
                            BranchCode = 36,
                            BranchCityCode = 1,
                            BranchName = "Branch 36"
                        },
                        new
                        {
                            BranchCode = 37,
                            BranchCityCode = 2,
                            BranchName = "Branch 37"
                        },
                        new
                        {
                            BranchCode = 38,
                            BranchCityCode = 3,
                            BranchName = "Branch 38"
                        },
                        new
                        {
                            BranchCode = 39,
                            BranchCityCode = 4,
                            BranchName = "Branch 39"
                        },
                        new
                        {
                            BranchCode = 40,
                            BranchCityCode = 5,
                            BranchName = "Branch 40"
                        },
                        new
                        {
                            BranchCode = 41,
                            BranchCityCode = 6,
                            BranchName = "Branch 41"
                        },
                        new
                        {
                            BranchCode = 42,
                            BranchCityCode = 7,
                            BranchName = "Branch 42"
                        },
                        new
                        {
                            BranchCode = 43,
                            BranchCityCode = 8,
                            BranchName = "Branch 43"
                        },
                        new
                        {
                            BranchCode = 44,
                            BranchCityCode = 9,
                            BranchName = "Branch 44"
                        },
                        new
                        {
                            BranchCode = 45,
                            BranchCityCode = 10,
                            BranchName = "Branch 45"
                        },
                        new
                        {
                            BranchCode = 46,
                            BranchCityCode = 11,
                            BranchName = "Branch 46"
                        },
                        new
                        {
                            BranchCode = 47,
                            BranchCityCode = 12,
                            BranchName = "Branch 47"
                        },
                        new
                        {
                            BranchCode = 48,
                            BranchCityCode = 13,
                            BranchName = "Branch 48"
                        },
                        new
                        {
                            BranchCode = 49,
                            BranchCityCode = 14,
                            BranchName = "Branch 49"
                        },
                        new
                        {
                            BranchCode = 50,
                            BranchCityCode = 15,
                            BranchName = "Branch 50"
                        },
                        new
                        {
                            BranchCode = 51,
                            BranchCityCode = 16,
                            BranchName = "Branch 51"
                        },
                        new
                        {
                            BranchCode = 52,
                            BranchCityCode = 17,
                            BranchName = "Branch 52"
                        },
                        new
                        {
                            BranchCode = 53,
                            BranchCityCode = 18,
                            BranchName = "Branch 53"
                        },
                        new
                        {
                            BranchCode = 54,
                            BranchCityCode = 19,
                            BranchName = "Branch 54"
                        },
                        new
                        {
                            BranchCode = 55,
                            BranchCityCode = 20,
                            BranchName = "Branch 55"
                        },
                        new
                        {
                            BranchCode = 56,
                            BranchCityCode = 21,
                            BranchName = "Branch 56"
                        },
                        new
                        {
                            BranchCode = 57,
                            BranchCityCode = 22,
                            BranchName = "Branch 57"
                        },
                        new
                        {
                            BranchCode = 58,
                            BranchCityCode = 23,
                            BranchName = "Branch 58"
                        },
                        new
                        {
                            BranchCode = 59,
                            BranchCityCode = 24,
                            BranchName = "Branch 59"
                        },
                        new
                        {
                            BranchCode = 60,
                            BranchCityCode = 25,
                            BranchName = "Branch 60"
                        },
                        new
                        {
                            BranchCode = 61,
                            BranchCityCode = 26,
                            BranchName = "Branch 61"
                        },
                        new
                        {
                            BranchCode = 62,
                            BranchCityCode = 27,
                            BranchName = "Branch 62"
                        },
                        new
                        {
                            BranchCode = 63,
                            BranchCityCode = 28,
                            BranchName = "Branch 63"
                        },
                        new
                        {
                            BranchCode = 64,
                            BranchCityCode = 29,
                            BranchName = "Branch 64"
                        },
                        new
                        {
                            BranchCode = 65,
                            BranchCityCode = 30,
                            BranchName = "Branch 65"
                        },
                        new
                        {
                            BranchCode = 66,
                            BranchCityCode = 31,
                            BranchName = "Branch 66"
                        },
                        new
                        {
                            BranchCode = 67,
                            BranchCityCode = 32,
                            BranchName = "Branch 67"
                        },
                        new
                        {
                            BranchCode = 68,
                            BranchCityCode = 33,
                            BranchName = "Branch 68"
                        },
                        new
                        {
                            BranchCode = 69,
                            BranchCityCode = 34,
                            BranchName = "Branch 69"
                        },
                        new
                        {
                            BranchCode = 70,
                            BranchCityCode = 35,
                            BranchName = "Branch 70"
                        },
                        new
                        {
                            BranchCode = 71,
                            BranchCityCode = 36,
                            BranchName = "Branch 71"
                        },
                        new
                        {
                            BranchCode = 72,
                            BranchCityCode = 1,
                            BranchName = "Branch 72"
                        },
                        new
                        {
                            BranchCode = 73,
                            BranchCityCode = 2,
                            BranchName = "Branch 73"
                        },
                        new
                        {
                            BranchCode = 74,
                            BranchCityCode = 3,
                            BranchName = "Branch 74"
                        },
                        new
                        {
                            BranchCode = 75,
                            BranchCityCode = 4,
                            BranchName = "Branch 75"
                        },
                        new
                        {
                            BranchCode = 76,
                            BranchCityCode = 5,
                            BranchName = "Branch 76"
                        },
                        new
                        {
                            BranchCode = 77,
                            BranchCityCode = 6,
                            BranchName = "Branch 77"
                        },
                        new
                        {
                            BranchCode = 78,
                            BranchCityCode = 7,
                            BranchName = "Branch 78"
                        },
                        new
                        {
                            BranchCode = 79,
                            BranchCityCode = 8,
                            BranchName = "Branch 79"
                        },
                        new
                        {
                            BranchCode = 80,
                            BranchCityCode = 9,
                            BranchName = "Branch 80"
                        },
                        new
                        {
                            BranchCode = 81,
                            BranchCityCode = 10,
                            BranchName = "Branch 81"
                        },
                        new
                        {
                            BranchCode = 82,
                            BranchCityCode = 11,
                            BranchName = "Branch 82"
                        },
                        new
                        {
                            BranchCode = 83,
                            BranchCityCode = 12,
                            BranchName = "Branch 83"
                        },
                        new
                        {
                            BranchCode = 84,
                            BranchCityCode = 13,
                            BranchName = "Branch 84"
                        },
                        new
                        {
                            BranchCode = 85,
                            BranchCityCode = 14,
                            BranchName = "Branch 85"
                        },
                        new
                        {
                            BranchCode = 86,
                            BranchCityCode = 15,
                            BranchName = "Branch 86"
                        },
                        new
                        {
                            BranchCode = 87,
                            BranchCityCode = 16,
                            BranchName = "Branch 87"
                        },
                        new
                        {
                            BranchCode = 88,
                            BranchCityCode = 17,
                            BranchName = "Branch 88"
                        },
                        new
                        {
                            BranchCode = 89,
                            BranchCityCode = 18,
                            BranchName = "Branch 89"
                        },
                        new
                        {
                            BranchCode = 90,
                            BranchCityCode = 19,
                            BranchName = "Branch 90"
                        },
                        new
                        {
                            BranchCode = 91,
                            BranchCityCode = 20,
                            BranchName = "Branch 91"
                        },
                        new
                        {
                            BranchCode = 92,
                            BranchCityCode = 21,
                            BranchName = "Branch 92"
                        },
                        new
                        {
                            BranchCode = 93,
                            BranchCityCode = 22,
                            BranchName = "Branch 93"
                        },
                        new
                        {
                            BranchCode = 94,
                            BranchCityCode = 23,
                            BranchName = "Branch 94"
                        },
                        new
                        {
                            BranchCode = 95,
                            BranchCityCode = 24,
                            BranchName = "Branch 95"
                        },
                        new
                        {
                            BranchCode = 96,
                            BranchCityCode = 25,
                            BranchName = "Branch 96"
                        },
                        new
                        {
                            BranchCode = 97,
                            BranchCityCode = 26,
                            BranchName = "Branch 97"
                        },
                        new
                        {
                            BranchCode = 98,
                            BranchCityCode = 27,
                            BranchName = "Branch 98"
                        },
                        new
                        {
                            BranchCode = 99,
                            BranchCityCode = 28,
                            BranchName = "Branch 99"
                        },
                        new
                        {
                            BranchCode = 100,
                            BranchCityCode = 29,
                            BranchName = "Branch 100"
                        });
                });

            modelBuilder.Entity("BankAccountOpening.Models.Cities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CityStateCode")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Mumbai",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Pune",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Bangalore",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Delhi",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Chennai",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Kolkata",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Hyderabad",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Ahmedabad",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Jaipur",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Surat",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Lucknow",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "Kanpur",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 13,
                            CityName = "Nagpur",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 14,
                            CityName = "Indore",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 15,
                            CityName = "Thane",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 16,
                            CityName = "Chandigarh",
                            CityStateCode = 4
                        },
                        new
                        {
                            CityId = 17,
                            CityName = "Patna",
                            CityStateCode = 10
                        },
                        new
                        {
                            CityId = 18,
                            CityName = "Vadodara",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 19,
                            CityName = "Coimbatore",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 20,
                            CityName = "Visakhapatnam",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 21,
                            CityName = "Bhopal",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 22,
                            CityName = "Nashik",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 23,
                            CityName = "Faridabad",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 24,
                            CityName = "Rajkot",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 25,
                            CityName = "Meerut",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 26,
                            CityName = "Noida",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 27,
                            CityName = "Shivamogga",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 28,
                            CityName = "Mysuru",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 29,
                            CityName = "Agra",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 30,
                            CityName = "Raipur",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 31,
                            CityName = "Vijayawada",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 32,
                            CityName = "Kochi",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 33,
                            CityName = "Gurgaon",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 34,
                            CityName = "Kozhikode",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 35,
                            CityName = "Ranchi",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 36,
                            CityName = "Howrah",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 37,
                            CityName = "Dhanbad",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 38,
                            CityName = "Jabalpur",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 39,
                            CityName = "Gwalior",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 40,
                            CityName = "Durgapur",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 41,
                            CityName = "Bhubaneswar",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 42,
                            CityName = "Tiruchirappalli",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 43,
                            CityName = "Vellore",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 44,
                            CityName = "Puducherry",
                            CityStateCode = 15
                        },
                        new
                        {
                            CityId = 45,
                            CityName = "Shimla",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 46,
                            CityName = "Dehradun",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 47,
                            CityName = "Mangalore",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 48,
                            CityName = "Gandhinagar",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 49,
                            CityName = "Srinagar",
                            CityStateCode = 1
                        },
                        new
                        {
                            CityId = 50,
                            CityName = "Amritsar",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 51,
                            CityName = "Allahabad",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 52,
                            CityName = "Bikaner",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 53,
                            CityName = "Jodhpur",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 54,
                            CityName = "Nagapattinam",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 55,
                            CityName = "Siliguri",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 56,
                            CityName = "Solapur",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 57,
                            CityName = "Cuttack",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 58,
                            CityName = "Udaipur",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 59,
                            CityName = "Raigarh",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 60,
                            CityName = "Haridwar",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 61,
                            CityName = "Kurnool",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 62,
                            CityName = "Jammu",
                            CityStateCode = 1
                        },
                        new
                        {
                            CityId = 63,
                            CityName = "Aurangabad",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 64,
                            CityName = "Bilaspur",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 65,
                            CityName = "Nellore",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 66,
                            CityName = "Erode",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 67,
                            CityName = "Tirunelveli",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 68,
                            CityName = "Warangal",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 69,
                            CityName = "Khammam",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 70,
                            CityName = "Muzaffarpur",
                            CityStateCode = 10
                        },
                        new
                        {
                            CityId = 71,
                            CityName = "Moradabad",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 72,
                            CityName = "Bihar Sharif",
                            CityStateCode = 10
                        },
                        new
                        {
                            CityId = 73,
                            CityName = "Shirdi",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 74,
                            CityName = "Guwahati",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 75,
                            CityName = "Rourkela",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 76,
                            CityName = "Bhilai",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 77,
                            CityName = "Madurai",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 78,
                            CityName = "Chandrapur",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 79,
                            CityName = "Ludhiana",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 80,
                            CityName = "Bilaspur",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 81,
                            CityName = "Kochi",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 82,
                            CityName = "Karur",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 83,
                            CityName = "Ambala",
                            CityStateCode = 4
                        },
                        new
                        {
                            CityId = 84,
                            CityName = "Haldwani",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 85,
                            CityName = "Aligarh",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 86,
                            CityName = "Tumkur",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 87,
                            CityName = "Sangli",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 88,
                            CityName = "Kolar",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 89,
                            CityName = "Jamshedpur",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 90,
                            CityName = "Rohtak",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 91,
                            CityName = "Shivpuri",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 92,
                            CityName = "Durgapur",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 93,
                            CityName = "Hoshiarpur",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 94,
                            CityName = "Gurgaon",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 95,
                            CityName = "Satna",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 96,
                            CityName = "Pondicherry",
                            CityStateCode = 15
                        },
                        new
                        {
                            CityId = 97,
                            CityName = "Baroda",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 98,
                            CityName = "Tumkur",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 99,
                            CityName = "Raichur",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 100,
                            CityName = "Vapi",
                            CityStateCode = 24
                        });
                });

            modelBuilder.Entity("BankAccountOpening.Models.Languages", b =>
                {
                    b.Property<int>("languageCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("languageCode"));

                    b.Property<string>("languageName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("languageCode");

                    b.ToTable("languages");

                    b.HasData(
                        new
                        {
                            languageCode = 1,
                            languageName = "Hindi"
                        },
                        new
                        {
                            languageCode = 2,
                            languageName = "Bengali"
                        },
                        new
                        {
                            languageCode = 3,
                            languageName = "Telugu"
                        },
                        new
                        {
                            languageCode = 4,
                            languageName = "Marathi"
                        },
                        new
                        {
                            languageCode = 5,
                            languageName = "Tamil"
                        },
                        new
                        {
                            languageCode = 6,
                            languageName = "Urdu"
                        },
                        new
                        {
                            languageCode = 7,
                            languageName = "Gujarati"
                        },
                        new
                        {
                            languageCode = 8,
                            languageName = "Malayalam"
                        },
                        new
                        {
                            languageCode = 9,
                            languageName = "Punjabi"
                        },
                        new
                        {
                            languageCode = 10,
                            languageName = "Odia"
                        },
                        new
                        {
                            languageCode = 11,
                            languageName = "Kannada"
                        },
                        new
                        {
                            languageCode = 12,
                            languageName = "Assamese"
                        },
                        new
                        {
                            languageCode = 13,
                            languageName = "Maithili"
                        },
                        new
                        {
                            languageCode = 14,
                            languageName = "Santali"
                        },
                        new
                        {
                            languageCode = 15,
                            languageName = "Konkani"
                        });
                });

            modelBuilder.Entity("BankAccountOpening.Models.States", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("states");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "Andhra Pradesh"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Arunachal Pradesh"
                        },
                        new
                        {
                            StateId = 3,
                            StateName = "Assam"
                        },
                        new
                        {
                            StateId = 4,
                            StateName = "Bihar"
                        },
                        new
                        {
                            StateId = 5,
                            StateName = "Chhattisgarh"
                        },
                        new
                        {
                            StateId = 6,
                            StateName = "Goa"
                        },
                        new
                        {
                            StateId = 7,
                            StateName = "Gujarat"
                        },
                        new
                        {
                            StateId = 8,
                            StateName = "Haryana"
                        },
                        new
                        {
                            StateId = 9,
                            StateName = "Himachal Pradesh"
                        },
                        new
                        {
                            StateId = 10,
                            StateName = "Jharkhand"
                        },
                        new
                        {
                            StateId = 11,
                            StateName = "Karnataka"
                        },
                        new
                        {
                            StateId = 12,
                            StateName = "Kerala"
                        },
                        new
                        {
                            StateId = 13,
                            StateName = "Madhya Pradesh"
                        },
                        new
                        {
                            StateId = 14,
                            StateName = "Maharashtra"
                        },
                        new
                        {
                            StateId = 15,
                            StateName = "Manipur"
                        },
                        new
                        {
                            StateId = 16,
                            StateName = "Meghalaya"
                        },
                        new
                        {
                            StateId = 17,
                            StateName = "Mizoram"
                        },
                        new
                        {
                            StateId = 18,
                            StateName = "Nagaland"
                        },
                        new
                        {
                            StateId = 19,
                            StateName = "Odisha"
                        },
                        new
                        {
                            StateId = 20,
                            StateName = "Punjab"
                        },
                        new
                        {
                            StateId = 21,
                            StateName = "Rajasthan"
                        },
                        new
                        {
                            StateId = 22,
                            StateName = "Sikkim"
                        },
                        new
                        {
                            StateId = 23,
                            StateName = "Tamil Nadu"
                        },
                        new
                        {
                            StateId = 24,
                            StateName = "Telangana"
                        },
                        new
                        {
                            StateId = 25,
                            StateName = "Tripura"
                        },
                        new
                        {
                            StateId = 26,
                            StateName = "Uttar Pradesh"
                        },
                        new
                        {
                            StateId = 27,
                            StateName = "Uttarakhand"
                        },
                        new
                        {
                            StateId = 28,
                            StateName = "West Bengal"
                        },
                        new
                        {
                            StateId = 29,
                            StateName = "Andaman and Nicobar Islands"
                        },
                        new
                        {
                            StateId = 30,
                            StateName = "Chandigarh"
                        },
                        new
                        {
                            StateId = 31,
                            StateName = "Dadra and Nagar Haveli and Daman and Diu"
                        },
                        new
                        {
                            StateId = 32,
                            StateName = "Delhi"
                        },
                        new
                        {
                            StateId = 33,
                            StateName = "Jammu and Kashmir"
                        },
                        new
                        {
                            StateId = 34,
                            StateName = "Ladakh"
                        },
                        new
                        {
                            StateId = 35,
                            StateName = "Lakshadweep"
                        },
                        new
                        {
                            StateId = 36,
                            StateName = "Puducherry"
                        });
                });

            modelBuilder.Entity("BankAccountOpening.Models.UserDetails", b =>
                {
                    b.Property<int>("FormNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormNo"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrefferedLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TypeOfAccount")
                        .HasColumnType("int");

                    b.Property<int>("title")
                        .HasColumnType("int");

                    b.HasKey("FormNo");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
