// <auto-generated />
using System;
using BankAccountOpening.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountOpening.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250425110613_Added City table")]
    partial class AddedCitytable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankAccountOpening.Models.Cities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CityStateCode")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Mumbai",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Pune",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Bangalore",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Delhi",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Chennai",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Kolkata",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Hyderabad",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Ahmedabad",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Jaipur",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Surat",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Lucknow",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "Kanpur",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 13,
                            CityName = "Nagpur",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 14,
                            CityName = "Indore",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 15,
                            CityName = "Thane",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 16,
                            CityName = "Chandigarh",
                            CityStateCode = 4
                        },
                        new
                        {
                            CityId = 17,
                            CityName = "Patna",
                            CityStateCode = 10
                        },
                        new
                        {
                            CityId = 18,
                            CityName = "Vadodara",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 19,
                            CityName = "Coimbatore",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 20,
                            CityName = "Visakhapatnam",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 21,
                            CityName = "Bhopal",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 22,
                            CityName = "Nashik",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 23,
                            CityName = "Faridabad",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 24,
                            CityName = "Rajkot",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 25,
                            CityName = "Meerut",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 26,
                            CityName = "Noida",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 27,
                            CityName = "Shivamogga",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 28,
                            CityName = "Mysuru",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 29,
                            CityName = "Agra",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 30,
                            CityName = "Raipur",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 31,
                            CityName = "Vijayawada",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 32,
                            CityName = "Kochi",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 33,
                            CityName = "Gurgaon",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 34,
                            CityName = "Kozhikode",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 35,
                            CityName = "Ranchi",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 36,
                            CityName = "Howrah",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 37,
                            CityName = "Dhanbad",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 38,
                            CityName = "Jabalpur",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 39,
                            CityName = "Gwalior",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 40,
                            CityName = "Durgapur",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 41,
                            CityName = "Bhubaneswar",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 42,
                            CityName = "Tiruchirappalli",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 43,
                            CityName = "Vellore",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 44,
                            CityName = "Puducherry",
                            CityStateCode = 15
                        },
                        new
                        {
                            CityId = 45,
                            CityName = "Shimla",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 46,
                            CityName = "Dehradun",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 47,
                            CityName = "Mangalore",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 48,
                            CityName = "Gandhinagar",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 49,
                            CityName = "Srinagar",
                            CityStateCode = 1
                        },
                        new
                        {
                            CityId = 50,
                            CityName = "Amritsar",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 51,
                            CityName = "Allahabad",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 52,
                            CityName = "Bikaner",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 53,
                            CityName = "Jodhpur",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 54,
                            CityName = "Nagapattinam",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 55,
                            CityName = "Siliguri",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 56,
                            CityName = "Solapur",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 57,
                            CityName = "Cuttack",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 58,
                            CityName = "Udaipur",
                            CityStateCode = 8
                        },
                        new
                        {
                            CityId = 59,
                            CityName = "Raigarh",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 60,
                            CityName = "Haridwar",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 61,
                            CityName = "Kurnool",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 62,
                            CityName = "Jammu",
                            CityStateCode = 1
                        },
                        new
                        {
                            CityId = 63,
                            CityName = "Aurangabad",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 64,
                            CityName = "Bilaspur",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 65,
                            CityName = "Nellore",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 66,
                            CityName = "Erode",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 67,
                            CityName = "Tirunelveli",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 68,
                            CityName = "Warangal",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 69,
                            CityName = "Khammam",
                            CityStateCode = 36
                        },
                        new
                        {
                            CityId = 70,
                            CityName = "Muzaffarpur",
                            CityStateCode = 10
                        },
                        new
                        {
                            CityId = 71,
                            CityName = "Moradabad",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 72,
                            CityName = "Bihar Sharif",
                            CityStateCode = 10
                        },
                        new
                        {
                            CityId = 73,
                            CityName = "Shirdi",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 74,
                            CityName = "Guwahati",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 75,
                            CityName = "Rourkela",
                            CityStateCode = 21
                        },
                        new
                        {
                            CityId = 76,
                            CityName = "Bhilai",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 77,
                            CityName = "Madurai",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 78,
                            CityName = "Chandrapur",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 79,
                            CityName = "Ludhiana",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 80,
                            CityName = "Bilaspur",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 81,
                            CityName = "Kochi",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 82,
                            CityName = "Karur",
                            CityStateCode = 13
                        },
                        new
                        {
                            CityId = 83,
                            CityName = "Ambala",
                            CityStateCode = 4
                        },
                        new
                        {
                            CityId = 84,
                            CityName = "Haldwani",
                            CityStateCode = 2
                        },
                        new
                        {
                            CityId = 85,
                            CityName = "Aligarh",
                            CityStateCode = 9
                        },
                        new
                        {
                            CityId = 86,
                            CityName = "Tumkur",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 87,
                            CityName = "Sangli",
                            CityStateCode = 14
                        },
                        new
                        {
                            CityId = 88,
                            CityName = "Kolar",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 89,
                            CityName = "Jamshedpur",
                            CityStateCode = 20
                        },
                        new
                        {
                            CityId = 90,
                            CityName = "Rohtak",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 91,
                            CityName = "Shivpuri",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 92,
                            CityName = "Durgapur",
                            CityStateCode = 19
                        },
                        new
                        {
                            CityId = 93,
                            CityName = "Hoshiarpur",
                            CityStateCode = 3
                        },
                        new
                        {
                            CityId = 94,
                            CityName = "Gurgaon",
                            CityStateCode = 7
                        },
                        new
                        {
                            CityId = 95,
                            CityName = "Satna",
                            CityStateCode = 23
                        },
                        new
                        {
                            CityId = 96,
                            CityName = "Pondicherry",
                            CityStateCode = 15
                        },
                        new
                        {
                            CityId = 97,
                            CityName = "Baroda",
                            CityStateCode = 24
                        },
                        new
                        {
                            CityId = 98,
                            CityName = "Tumkur",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 99,
                            CityName = "Raichur",
                            CityStateCode = 11
                        },
                        new
                        {
                            CityId = 100,
                            CityName = "Vapi",
                            CityStateCode = 24
                        });
                });

            modelBuilder.Entity("BankAccountOpening.Models.States", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("states");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "Andhra Pradesh"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Arunachal Pradesh"
                        },
                        new
                        {
                            StateId = 3,
                            StateName = "Assam"
                        },
                        new
                        {
                            StateId = 4,
                            StateName = "Bihar"
                        },
                        new
                        {
                            StateId = 5,
                            StateName = "Chhattisgarh"
                        },
                        new
                        {
                            StateId = 6,
                            StateName = "Goa"
                        },
                        new
                        {
                            StateId = 7,
                            StateName = "Gujarat"
                        },
                        new
                        {
                            StateId = 8,
                            StateName = "Haryana"
                        },
                        new
                        {
                            StateId = 9,
                            StateName = "Himachal Pradesh"
                        },
                        new
                        {
                            StateId = 10,
                            StateName = "Jharkhand"
                        },
                        new
                        {
                            StateId = 11,
                            StateName = "Karnataka"
                        },
                        new
                        {
                            StateId = 12,
                            StateName = "Kerala"
                        },
                        new
                        {
                            StateId = 13,
                            StateName = "Madhya Pradesh"
                        },
                        new
                        {
                            StateId = 14,
                            StateName = "Maharashtra"
                        },
                        new
                        {
                            StateId = 15,
                            StateName = "Manipur"
                        },
                        new
                        {
                            StateId = 16,
                            StateName = "Meghalaya"
                        },
                        new
                        {
                            StateId = 17,
                            StateName = "Mizoram"
                        },
                        new
                        {
                            StateId = 18,
                            StateName = "Nagaland"
                        },
                        new
                        {
                            StateId = 19,
                            StateName = "Odisha"
                        },
                        new
                        {
                            StateId = 20,
                            StateName = "Punjab"
                        },
                        new
                        {
                            StateId = 21,
                            StateName = "Rajasthan"
                        },
                        new
                        {
                            StateId = 22,
                            StateName = "Sikkim"
                        },
                        new
                        {
                            StateId = 23,
                            StateName = "Tamil Nadu"
                        },
                        new
                        {
                            StateId = 24,
                            StateName = "Telangana"
                        },
                        new
                        {
                            StateId = 25,
                            StateName = "Tripura"
                        },
                        new
                        {
                            StateId = 26,
                            StateName = "Uttar Pradesh"
                        },
                        new
                        {
                            StateId = 27,
                            StateName = "Uttarakhand"
                        },
                        new
                        {
                            StateId = 28,
                            StateName = "West Bengal"
                        },
                        new
                        {
                            StateId = 29,
                            StateName = "Andaman and Nicobar Islands"
                        },
                        new
                        {
                            StateId = 30,
                            StateName = "Chandigarh"
                        },
                        new
                        {
                            StateId = 31,
                            StateName = "Dadra and Nagar Haveli and Daman and Diu"
                        },
                        new
                        {
                            StateId = 32,
                            StateName = "Delhi"
                        },
                        new
                        {
                            StateId = 33,
                            StateName = "Jammu and Kashmir"
                        },
                        new
                        {
                            StateId = 34,
                            StateName = "Ladakh"
                        },
                        new
                        {
                            StateId = 35,
                            StateName = "Lakshadweep"
                        },
                        new
                        {
                            StateId = 36,
                            StateName = "Puducherry"
                        });
                });

            modelBuilder.Entity("BankAccountOpening.Models.UserDetails", b =>
                {
                    b.Property<int>("FormNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormNo"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrefferedLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TypeOfAccount")
                        .HasColumnType("int");

                    b.Property<int>("title")
                        .HasColumnType("int");

                    b.HasKey("FormNo");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
